version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: moonlight_test_user
          POSTGRES_DB: moonlight_test
          POSTGRES_PASSWORD: "test"
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-v30-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          - dependencies-v30-{{ checksum "project/plugins.sbt" }}
          - dependencies-v30
      - restore_cache:
          keys:
          - target-v30-{{ .Branch }}
          - target-v30
      - run: sbt coverage test coverageReport
      - run: bash <(curl -s https://codecov.io/bash) -Z
      - run: mkdir -p ./target/junit && cp -R ./target/test-reports ./target/junit/test-reports
      - save_cache:
          paths:
            - target
          key: target-v30-{{ .Branch }}
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: dependencies-v30-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
      - store_artifacts:
          path: /tmp/screenshots
      - store_test_results:
          path: ./target/junit