web: ./target/universal/stage/bin/test-project -Dconfig.resource=heroku.conf
worker: ./target/universal/stage/bin/test-project -Dconfig.resource=heroku.conf -main givers.moonlight.Main -- prod coordinate
